In [35]:
from PIL import Image
import numpy as np
import pandas as pd
from sklearn import decomposition
from sklearn.svm import SVC
from pylab import * 
from sklearn.cross_validation import train_test_split
from os import listdir
from os.path import isfile, join

DIMENSION = 32
ROOT_DIR = "C:/Users/Dameria Desi/Documents/TA/IMAGE/images/best_seller"
ROOT_DIR2 = "C:/Users/Dameria Desi/Documents/TA/IMAGE/images/non_best_seller"
BEST = "best_seller"
NBEST = "non_best_seller"
CLASSES = [BEST, NBEST]

def getData(generateTuningData):
    trainingData = {}
    tuneData = {}
    testData = {}
    for clazz in CLASSES:
        (train, tune, test) = buildTrainTestVectors(buildImageList(ROOT_DIR + clazz + "/"), generateTuningData)
        trainingData[clazz] = train
        tuneData[clazz] = tune
        testData[clazz] = test

    return (trainingData, tuneData, testData)

def buildImageList(dirName):
    imgs = [Image.open(dirName + fileName).resize((DIMENSION, DIMENSION)) for fileName in os.listdir(dirName)]
    imgs = [list(itertools.chain.from_iterable(img.getdata())) for img in imgs]
    return imgs

Best = [f for f in listdir(ROOT_DIR) if isfile(join(ROOT_DIR, f))]
NBest = [f for f in listdir(ROOT_DIR) if isfile(join(ROOT_DIR2, f))]

for i in Best:
 Image.open(join(ROOT_DIR,i))
 a = Image.open(join(ROOT_DIR,i)) 
matrix_Best = array([array(a).flatten()
                  for i in Best],'f')

pca = decomposition.PCA(n_components=10) # dimensional reduction PCA
pca.fit(matrix_Best)

for i in NBest:
 Image.open(join(ROOT_DIR2,i))
 b = Image.open(join(ROOT_DIR2,i)) 
matrix_NBest = array([array(b).flatten()
                  for i in NBest ],'f')
pca = decomposition.PCA(n_components=10) # dimensional reduction PCA
pca.fit(matrix_NBest)

visual_fiture= []
for i in Best:
    visual_fiture.append(matrix_Best);

for i in Best:
    visual_fiture.append(matrix_NBest);


kategori_list= []
for k in range(len(Best)):
   kategori_list.append("yes" );  

for k in range(len(NBest)):
   kategori_list.append("no");
data = pd.DataFrame([list(visual_fiture),list(kategori_list)])
data = data.T


In [36]:
data


0    1
0   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
1   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
2   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
3   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
4   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
5   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
6   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
7   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
8   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
9   [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...  yes
10  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
11  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
12  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
13  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
14  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
15  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
16  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
17  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
18  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no
19  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...   no

In [30]:
X = data.iloc[:,:-1]
X.head()

0
0  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...
1  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...
2  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...
3  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...
4  [[255.0, 255.0, 255.0, 255.0, 255.0, 255.0, 25...

In [44]:
from sklearn.preprocessing import LabelEncoder
y = data.iloc[:,-1]


category_encoder = LabelEncoder()
y = category_encoder.fit_transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(visual_fiture, y, test_size=0.2, random_state=1)

In [47]:
X_train

[array([[ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        ..., 
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.]], dtype=float32),
 array([[ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        ..., 
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.]], dtype=float32),
 array([[ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        ..., 
        [ 255.,  255.,  255., ...,  255.,  255.,  255.],
        [ 25

In [48]:
from sklearn.svm import SVC
from sklearn import metrics
svc = SVC()
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
print('Accuracy scoreL')
print(metrics.accuracy_score(y_test,y_pred))

ValueError: Found array with dim 3. Estimator expected <= 2.